export interface LanguageOption {
  code: string;
  name: string;
  native: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  // Central Asia & CIS
  { code: "uz", name: "Uzbek", native: "Oʻzbekcha", flag: "🇺🇿" },
  { code: "ru", name: "Russian", native: "Русский", flag: "🇷🇺" },
  { code: "kk", name: "Kazakh", native: "Қазақша", flag: "🇰🇿" },
  { code: "ky", name: "Kyrgyz", native: "Кыргызча", flag: "🇰🇬" },
  { code: "tg", name: "Tajik", native: "Тоҷикӣ", flag: "🇹🇯" },
  { code: "tk", name: "Turkmen", native: "Türkmençe", flag: "🇹🇲" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycanca", flag: "🇦🇿" },
  { code: "hy", name: "Armenian", native: "Հայերեն", flag: "🇦🇲" },
  { code: "ka", name: "Georgian", native: "ქართული", flag: "🇬🇪" },
  { code: "uk", name: "Ukrainian", native: "Українська", flag: "🇺🇦" },
  { code: "be", name: "Belarusian", native: "Беларуская", flag: "🇧🇾" },
  // Europe
  { code: "en-GB", name: "English (UK)", native: "English (UK)", flag: "🇬🇧" },
  { code: "en-US", name: "English (US)", native: "English (US)", flag: "🇺🇸" },
  { code: "de", name: "German", native: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "French", native: "Français", flag: "🇫🇷" },
  { code: "es", name: "Spanish", native: "Español", flag: "🇪🇸" },
  { code: "pt", name: "Portuguese", native: "Português", flag: "🇵🇹" },
  { code: "it", name: "Italian", native: "Italiano", flag: "🇮🇹" },
  { code: "nl", name: "Dutch", native: "Nederlands", flag: "🇳🇱" },
  { code: "pl", name: "Polish", native: "Polski", flag: "🇵🇱" },
  { code: "cs", name: "Czech", native: "Čeština", flag: "🇨🇿" },
  { code: "sv", name: "Swedish", native: "Svenska", flag: "🇸🇪" },
  { code: "no", name: "Norwegian", native: "Norsk", flag: "🇳🇴" },
  { code: "fi", name: "Finnish", native: "Suomi", flag: "🇫🇮" },
  { code: "da", name: "Danish", native: "Dansk", flag: "🇩🇰" },
  { code: "ro", name: "Romanian", native: "Română", flag: "🇷🇴" },
  { code: "hu", name: "Hungarian", native: "Magyar", flag: "🇭🇺" },
  { code: "el", name: "Greek", native: "Ελληνικά", flag: "🇬🇷" },
  { code: "bg", name: "Bulgarian", native: "Български", flag: "🇧🇬" },
  { code: "sr", name: "Serbian", native: "Српски", flag: "🇷🇸" },
  { code: "hr", name: "Croatian", native: "Hrvatski", flag: "🇭🇷" },
  { code: "sk", name: "Slovak", native: "Slovenčina", flag: "🇸🇰" },
  // Asia
  { code: "zh-CN", name: "Chinese (Simplified)", native: "简体中文", flag: "🇨🇳" },
  { code: "zh-TW", name: "Chinese (Traditional)", native: "繁體中文", flag: "🇹🇼" },
  { code: "ja", name: "Japanese", native: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", native: "한국어", flag: "🇰🇷" },
  { code: "hi", name: "Hindi", native: "हिन्दी", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", native: "বাংলা", flag: "🇧🇩" },
  { code: "ur", name: "Urdu", native: "اردو", flag: "🇵🇰" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "tl", name: "Tagalog", native: "Tagalog", flag: "🇵🇭" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt", flag: "🇻🇳" },
  { code: "th", name: "Thai", native: "ไทย", flag: "🇹🇭" },
  // Middle East
  { code: "ar", name: "Arabic", native: "العربية", flag: "🇸🇦" },
  { code: "tr", name: "Turkish", native: "Türkçe", flag: "🇹🇷" },
  { code: "fa", name: "Persian", native: "فارسی", flag: "🇮🇷" },
  { code: "he", name: "Hebrew", native: "עברית", flag: "🇮🇱" },
  { code: "sw", name: "Swahili", native: "Kiswahili", flag: "🇰🇪" },
  // Americas
  { code: "pt-BR", name: "Brazilian Portuguese", native: "Português (BR)", flag: "🇧🇷" },
];

const DICT: Record<string, Record<string, string>> = {
  ru: {
    app_name: "UKA Messenger",
    start: "Начать",
    secure: "Безопасность",
    style: "Стиль",
    ai_translate: "AI-переводчик",
    smart_convert: "Умный конвертер",
    hero_tag: "Месенджер нового поколения",
    hero_title: "Общайся стильно. Защищённо. Без границ.",
    hero_sub: "UKA Messenger — киберпанк-эстетика, мгновенные сообщения и встроенный AI-перевод.",
    sign_in: "Войти",
    sign_in_google: "Войти через Google",
    email: "Email",
    code: "Код подтверждения",
    send_code: "Отправить код",
    verify: "Подтвердить",
    chats: "Чаты",
    all: "Все",
    direct: "Личные",
    groups: "Группы",
    channels: "Каналы",
    settings: "Настройки",
    admin: "Админ-панель",
    logout: "Выйти",
    type_message: "Напишите сообщение…",
    send: "Отправить",
    first_name: "Имя",
    last_name: "Фамилия",
    username: "Юзернейм",
    phone: "Номер телефона",
    country: "Страна",
    language: "Язык интерфейса",
    save: "Сохранить",
    saved: "Сохранено",
    new_chat: "Новый чат",
    search_user: "Поиск по @username или телефону",
    no_chats: "Нет чатов. Начните новый!",
    select_chat: "Выберите чат, чтобы начать общение",
    onboarding_title: "Завершите регистрацию",
    onboarding_sub: "Эти данные нужны, чтобы друзья смогли вас найти",
  },
  en: {
    app_name: "UKA Messenger",
    start: "Get started",
    secure: "Security",
    style: "Style",
    ai_translate: "AI Translator",
    smart_convert: "Smart Converter",
    hero_tag: "Next-gen messenger",
    hero_title: "Chat with style. Encrypted. Borderless.",
    hero_sub: "UKA Messenger — cyberpunk aesthetic, instant messaging and built-in AI translation.",
    sign_in: "Sign in",
    sign_in_google: "Sign in with Google",
    email: "Email",
    code: "Verification code",
    send_code: "Send code",
    verify: "Verify",
    chats: "Chats",
    all: "All",
    direct: "Direct",
    groups: "Groups",
    channels: "Channels",
    settings: "Settings",
    admin: "Admin",
    logout: "Sign out",
    type_message: "Type a message…",
    send: "Send",
    first_name: "First name",
    last_name: "Last name",
    username: "Username",
    phone: "Phone",
    country: "Country",
    language: "Interface language",
    save: "Save",
    saved: "Saved",
    new_chat: "New chat",
    search_user: "Search by @username or phone",
    no_chats: "No chats yet. Start a new one!",
    select_chat: "Pick a chat to start messaging",
    onboarding_title: "Finish your sign-up",
    onboarding_sub: "Friends will use this info to find you",
  },
  uz: {
    app_name: "UKA Messenger",
    start: "Boshlash",
    secure: "Xavfsizlik",
    style: "Uslub",
    ai_translate: "AI tarjimon",
    smart_convert: "Aqlli oʻgirgich",
    hero_tag: "Yangi avlod messenjeri",
    hero_title: "Uslubli muloqot. Himoyalangan. Chegarasiz.",
    hero_sub: "UKA Messenger — kiberpunk uslubi, tezkor xabarlar va oʻrnatilgan AI tarjima.",
    sign_in: "Kirish",
    sign_in_google: "Google orqali kirish",
    email: "Email",
    code: "Tasdiqlash kodi",
    send_code: "Kod yuborish",
    verify: "Tasdiqlash",
    chats: "Chatlar",
    all: "Hammasi",
    direct: "Shaxsiy",
    groups: "Guruhlar",
    channels: "Kanallar",
    settings: "Sozlamalar",
    admin: "Admin",
    logout: "Chiqish",
    type_message: "Xabar yozing…",
    send: "Yuborish",
    first_name: "Ism",
    last_name: "Familiya",
    username: "Foydalanuvchi nomi",
    phone: "Telefon",
    country: "Davlat",
    language: "Interfeys tili",
    save: "Saqlash",
    saved: "Saqlandi",
    new_chat: "Yangi chat",
    search_user: "@username yoki telefon boʻyicha qidirish",
    no_chats: "Hali chatlar yoʻq. Yangisini boshlang!",
    select_chat: "Yozish uchun chatni tanlang",
    onboarding_title: "Roʻyxatdan oʻtishni yakunlang",
    onboarding_sub: "Doʻstlaringiz sizni shu maʼlumotlar orqali topadi",
  },
};

export function t(lang: string, key: string): string {
  const base = lang.split("-")[0];
  return DICT[lang]?.[key] ?? DICT[base]?.[key] ?? DICT.en[key] ?? key;
}
